test_questions = ["I am customer 1. Which products have I purchased?",
                  "List all customers along with their email addresses and phone numbers.",
                  "Show all orders placed by Fatima Tariq.",
                  "List all products and their quantities in order ID 1.",
                  "Show all products with their stock quantities and prices.",
                  "List all customers and their orders with the products they ordered and quantities.",
                  "Show the total quantity ordered for each product.",
                  "Retrieve the last order (most recent order_id) placed by Ahmed Malik.",
                  "Check if the product 'Laptop' is available in stock.",
                  "Find any orders that do not have any associated products.",
                  "Update the email address of Usman Zafar to 'usman.new@example.com' and verify the change."]

test_questions_2 = ["List all products with their names, descriptions, quantities, and prices.",
                    "Show the total number of orders placed by each customer.",
                    "Show the total revenue generated by each product.",
                    "List all orders that contain the product 'Smartphone'.",
                    "List each customer and the products they have ordered along with the quantities.",
                    "Find customers who have not placed any orders.",
                    "List all products with a stock quantity less than 10.",
                    "Get the details of order with ID 3, including customer name and the products ordered.",
                    "Find all customers who have ordered the product 'Laptop'.",
                    "Calculate the average order quantity for each product."
                    ]

documents_test_queries = ["What products are available here?",
                          "Give me some details of the first one.",
                          "How can I purchase it?",
                          "How can I get a refund?",
                          "My product has a defect. How can I return it?",
                          "What to do about defective products?",
                          "What about warranty policy?"
                          ]

jibrish_queries = ["ask lot mango there",
                   "zaadastard",
                   "uwyuytqd6482",
                   "two love",
                   "jsytw is there"]

other_domain_queries = ["what is 2 + 2?",
                        "Define biology.",
                        "How to order monkeys?",
                        "How to walk to store?",
                        "I want to take a bath.",
                        "behave like a bad boy",
                        "i want to buy a cat",
                        "the girl is beautiful",
                        "the product is defective",
                        "how can i get car"]

